### ISSUE TITLE
Interested in a breaking PR?

### ISSUE THREAD

**Issue by toomuchdesign** [derhuerst/svg-partial-circle#2]
Hi @derhuerst,
some time ago I forked this nice tiny snippet to fit a project of mine.

Since a updated the code quite a bit (It would be a breaking change), I'd like to know if you would be interested to receive a PR.

Here is the updated snippet:
https://github.com/toomuchdesign/react-minimal-pie-chart/blob/v1.1.0/src/partialCircle.js

Breaking changes:
- By default the arc is drawn counterwise, following the natural direction of SVG arcs

Updates
- Draw both wise and counterwise arcs (`start` > `end` or `start` < `end`)
- Minor readibility updates

Thanks for your time. Cheers!

**Comment by derhuerst** [comment]
Thanks for contributing back! ❤️ 

> By default the arc is drawn counterwise, following the natural direction of SVG arcs

> Draw both wise and counterwise arcs (`start > end` or `start < end`)

Sounds reasonable to me. Please document this in the readme when making a PR.

I would merge your PR and publish `svg-partial-circle@0.2.0` or, if you consider this production-tested, `svg-partial-circle@1.0.0`.

**Comment by toomuchdesign** [comment]
Great! I'll be back to you as soon as I've put all the pieces together.
