### ISSUE TITLE
Can't specify direction

### ISSUE THREAD

**Issue by lukepighetti** [derhuerst/svg-partial-circle#4]
If I have start > end and end > start, the drawing result is the same. How do I specify direction? Can't make a pie chart without being able to specify cw or ccw direction.

**Comment by derhuerst** [comment]
If I understand you correctly (and my 2-years-old code), you should be able to specify a direction via `start` & `end`, but only see it, e.g. if you [give it a marker](https://stackoverflow.com/questions/11808860/how-to-place-arrow-head-triangles-on-svg-lines). Please let me know if that works!

**Comment by lukepighetti** [comment]
Lets say you want to make an arc that is 300 degrees and one that is 60 degrees. I cannot reliably specify whether the arc is 300 or 60. It seems to have a mind of its own. That's what I mean by clockwise vs counter-clockwise. Changing start/end doesn't seem to matter.

**Comment by lukepighetti** [comment]
For what it's worth this is super low priority and I know this package is unlikely to be maintained, just wondering if there was a simple way to do it with the package as it exists. Thanks!

**Comment by derhuerst** [comment]
I've pushed [an example that demonstrates how to do different directions](https://github.com/derhuerst/svg-partial-circle/blob/412016e683aa838a5dca201eca17a238d55aa430/example.js). It yields this for me:


![Screenshot 2019-12-28 at 20 11 33](https://user-images.githubusercontent.com/5072613/71548441-511b1880-29ae-11ea-8e11-f5d46e3aa905.png)

**Comment by derhuerst** [comment]
In order to keep an overview, I will close this. Please reopen if you still have a question or want to report this as a bug.
